patterns = {
    "what is your Age": [
     "I am program i don't age ;)",
     "Ai don't age",
     "I am not human so i don't age",
     "I am created in 2024 you can calculate",
],
    "How are you?": [
        "I'm doing well, thank you!",
        "All good here!",
        "I'm fine, thanks for asking.",
        "Not too bad, thanks!",
        "I'm great, how about you?"
    ],
    "¿Cómo estás?": [
        "¡Estoy bien, gracias!",
        "¡Todo bien aquí!",
        "¡Estoy bien, gracias por preguntar!",
        "¡No muy mal, gracias!",
        "¡Estoy genial, ¿y tú?"
    ],
    "Comment ça va?": [
        "Je vais bien, merci!",
        "Tout va bien ici!",
        "Ça va bien, merci de demander!",
        "Pas trop mal, merci!",
        "Je vais super bien, et toi?"
    ],
    "Wie geht es dir?": [
        "Mir geht es gut, danke!",
        "Alles gut hier!",
        "Mir geht es gut, danke fürs Fragen!",
        "Nicht schlecht, danke!",
        "Mir geht es super, und dir?"
    ],
    "Come stai?": [
        "Sto bene, grazie!",
        "Tutto bene qui!",
        "Sto bene, grazie di chiedere!",
        "Non male, grazie!",
        "Sto benissimo, e tu?"
    ],
    "Como você está?": [
        "Estou bem, obrigado!",
        "Tudo bem aqui!",
        "Estou bem, obrigado por perguntar!",
        "Não muito mal, obrigado!",
        "Estou ótimo, e você?"
    ],
    "Как дела?": [
        "У меня всё хорошо, спасибо!",
        "Всё в порядке!",
        "У меня всё отлично, спасибо за спрос!",
        "Не плохо, спасибо!",
        "У меня всё замечательно, а у вас?"
    ],
    "你好吗?": [
        "我很好, 谢谢!",
        "一切都好!",
        "我很好, 谢谢你的问候!",
        "还行, 谢谢!",
        "我很棒, 你呢?"
    ],
    "How's it going?": [
        "It's going well, thanks!",
        "Everything's going smoothly!",
        "Not too bad, thanks!",
        "Great, thanks for asking!",
        "Can't complain, thanks!"
    ],
    "¿Qué tal?": [
        "¡Va bien, gracias!",
        "¡Todo está yendo bien!",
        "¡No muy mal, gracias!",
        "¡Genial, gracias por preguntar!",
        "¡No me puedo quejar, gracias!"
    ],
    "How's your day?": [
        "My day is going well, thank you!",
        "It's been a good day so far!",
        "Not too shabby, thanks!",
        "Great, thanks for asking!",
        "My day's been fantastic, how about yours?"
    ],
    "¿Cómo ha sido tu día?": [
        "¡Mi día está yendo bien, gracias!",
        "¡Hasta ahora ha sido un buen día!",
        "¡No está mal, gracias!",
        "¡Genial, gracias por preguntar!",
        "¡Mi día ha sido fantástico, ¿y el tuyo?"
    ],
    "Comment s'est passée ta journée?": [
        "Ma journée se passe bien, merci!",
        "Ça a été une bonne journée jusqu'à présent!",
        "Pas mal, merci!",
        "Génial, merci de demander!",
        "Ma journée a été fantastique, et la tienne?"
    ],
    "How are you?": ["I'm doing well, thank you!", "All good here!", "I'm fine, thanks for asking.", "Not too bad, thanks!", "I'm great, how about you?"],
    "¿Cómo estás?": ["¡Estoy bien, gracias!", "¡Todo bien aquí!", "¡Estoy bien, gracias por preguntar!", "¡No muy mal, gracias!", "¡Estoy genial, ¿y tú?"],
    "Comment ça va?": ["Je vais bien, merci!", "Tout va bien ici!", "Ça va bien, merci de demander!", "Pas trop mal, merci!", "Je vais super bien, et toi?"],
    "Wie geht es dir?": ["Mir geht es gut, danke!", "Alles gut hier!", "Mir geht es gut, danke fürs Fragen!", "Nicht schlecht, danke!", "Mir geht es super, und dir?"],
    "Come stai?": ["Sto bene, grazie!", "Tutto bene qui!", "Sto bene, grazie di chiedere!", "Non male, grazie!", "Sto benissimo, e tu?"],
    "Como você está?": ["Estou bem, obrigado!", "Tudo bem aqui!", "Estou bem, obrigado por perguntar!", "Não muito mal, obrigado!", "Estou ótimo, e você?"],
    "Как дела?": ["У меня всё хорошо, спасибо!", "Всё в порядке!", "У меня всё отлично, спасибо за спрос!", "Не плохо, спасибо!", "У меня всё замечательно, а у вас?"],
    "你好吗?": ["我很好, 谢谢!", "一切都好!", "我很好, 谢谢你的 问候!", "还行, 谢谢!", "我很棒, 你呢?"],
    "How's it going?": ["It's going well, thanks!", "Everything's going smoothly!", "Not too bad, thanks!", "Great, thanks for asking!", "Can't complain, thanks!"],
    "¿Qué tal?": ["¡Va bien, gracias!", "¡Todo está yendo bien!", "¡No muy mal, gracias!", "¡Genial, gracias por preguntar!", "¡No me puedo quejar, gracias!"],
    "How's your day?": ["My day is going well, thank you!", "It's been a good day so far!", "Not too shabby, thanks!", "Great, thanks for asking!", "My day's been fantastic, how about yours?"],
    "¿Cómo ha sido tu día?": ["¡Mi día está yendo bien, gracias!", "¡Hasta ahora ha sido un buen día!", "¡No está mal, gracias!", "¡Genial, gracias por preguntar!", "¡Mi día ha sido fantástico, ¿y el tuyo?"],
    "Comment s'est passée ta journée?": ["Ma journée se passe bien, merci!", "Ça a été une bonne journée jusqu'à présent!", "Pas mal, merci!", "Génial, merci de demander!", "Ma journée a été fantastique, et la tienne?"],
    "Wie war dein Tag?": ["Mein Tag läuft gut, danke!", "Es war ein guter Tag bisher!", "Nicht schlecht, danke!", "Super, danke fürs Fragen!", "Mein Tag war fantastisch, wie war deiner?"],
    "Come è stata la tua giornata?": ["La mia giornata sta andando bene, grazie!", "È stata una buona giornata finora!", "Non male, grazie!", "Fantastica, grazie per aver chiesto!", "La mia giornata è stata fantastica, la tua?"],
    "Como foi o seu dia?": ["Meu dia está indo bem, obrigado!", "Foi um bom dia até agora!", "Não muito ruim, obrigado!", "Ótimo, obrigado por perguntar!", "Meu dia foi fantástico, e o seu?"],
    "Как прошел ваш день?": ["Мой день прошел хорошо, спасибо!", "До сих пор был хороший день!", "Не плохо, спасибо!", "Отлично, спасибо за вопрос!", "Мой день был фантастическим, как ваш?"],
    "你今天过得怎么样?": ["我今天过得很好, 谢谢!", "到目前 为止 一切都很顺利!", "还不错, 谢谢!", "很 棒, 谢谢你的问候!", "我的一 天过得很棒, 你呢?"],
    "How's the weather?": ["The weather is nice today, thank you!", "It's sunny and pleasant!", "Not too bad, thanks!", "Great, thanks for asking!", "The weather's fantastic, how about where you are?"],
    "¿Cómo está el clima?": ["El clima está agradable hoy, ¡gracias!", "¡Está soleado y agradable!", "No está mal, gracias!", "¡Genial, gracias por preguntar!", "¡El clima está fantástico, ¿y en donde estás tú?"],
    "Haha": ["😄 Glad I could make you laugh!", "😆 Haha, I'm glad you found that amusing!", "😂 Haha, laughter is the best medicine!", "🤣 Haha, I aim to entertain!", "😄 Haha, spreading some cheer your way!", "😆 Haha, laughter is contagious!", "😂 Haha, I'm delighted to bring a smile to your face!", "🤣 Haha, I'm here to brighten your day!", "😄 Haha, glad I could bring a chuckle to your day!", "😆 Haha, that's hilarious!"],
    "LOL": ["😄 LOL, glad I could make you laugh!", " 😆 LOL, laughter is the best medicine!", "😂 LOL, I'm here to bring some joy!", "🤣 LOL, I aim to entertain!", "😄 LOL, spreading some cheer your way!", "😆 LOL, laughter is contagious!", "😂 LOL, I'm delighted to bring a smile to your face!", "🤣 LOL, I'm here to brighten your day!", "😄 LOL, glad I could bring a chuckle to your day!", "😆 LOL, that's hilarious!"],
    "Hahaha": ["😄 Hahaha, glad I could make you laugh!", "😆 Hahaha, laughter is the best medicine!", "😂 Hahaha, I'm here to bring some joy!", "🤣 Hahaha, I aim to entertain!", "😄 Hahaha, spreading some cheer your way!", "😆 Hahaha, laughter is contagious!", " 😂 Hahaha, I'm delighted to bring a smile to your face!", "🤣 Hahaha, I'm here to brighten your day!", "😄 Hahaha, glad I could bring a chuckle to your day!", "😆 Hahaha, that's hilarious!"],
    "LOL, that's funny": ["😄 Haha, I'm glad you found it funny!", "😆 LOL, laughter is the best response!", "😂 Haha, I aim to entertain!", "🤣 LOL, spreading some cheer your way!", "😄 Haha, laughter is contagious!", "😆 LOL, I'm delighted to bring a smile to your face!", "😂 Haha, I'm here to brighten your day!", " 🤣 LOL, glad I could bring a chuckle to your day!", "😄 Haha, that's hilarious!", " 😆 LOL, you're cracking me up!"],
    "That's hilarious!": ["😄 Haha, I'm glad you found it hilarious!", "😆 LOL, laughter is the best response!", "😂 Haha, I aim to entertain!", "🤣 LOL, spreading some cheer your way!", "😄 Haha, laughter is contagious!", "😆 LOL, I'm delighted to bring a smile to your face!", "😂 Haha, I'm here to brighten your day!", " 🤣 LOL, glad I could bring a chuckle to your day!", " 😄 Haha, that's hilarious!", "😆 LOL, you're cracking me up!"],
    "You're funny!": ["😄 Haha, glad I could make you laugh!", "😆 LOL, laughter is the best medicine!", "😂 Haha, I aim to entertain!", "🤣 LOL, spreading some cheer your way!", "😄 Haha, laughter is contagious!", "😆 LOL, I'm delighted to bring a smile to your face!", "😂 Haha, I'm here to brighten your day!", "🤣 LOL, glad I could bring a chuckle to your day!", "😄 Haha, that's hilarious!", "😆 LOL, you're cracking me up!"],
    "How are you?": ["I'm doing well, thank you!", "All good here, how about you?", "I'm feeling great, thanks for asking!", "Not too bad, thanks for checking in!", "I'm fine, hope you're doing well too!", "I'm doing fine, thanks!", "I'm great, how can I assist you?", "I'm doing well, hope you're having a good day too!", "I'm good, how can I help you?", "I'm good, thanks!"],
    "What's up?": ["Not much, just here to assist you!", "Just hanging out, ready to help!", "Just taking care of business, how about you?", "Nothing much, what's on your mind?", "Just here, eager to chat!", "Just enjoying the day, what about you?", "Not a whole lot, how can I assist you?", "Just keeping busy, what can I do for you?", "Just taking it easy, what's going on with you?", "Nothing exciting, just here to help!"],
    "How's it going?": ["It's going well, thanks for asking!", "Going great here, how about you?", "Going smoothly, how's everything on your end?", "Going pretty good, what's up with you?", "It's going fine, what can I do for you?", "Going alright, thanks for checking in!", "Going good, how can I assist you?", "Going fine, hope everything's going well for you too!", "It's going well, what's on your mind?", "Going great, thanks for asking!"],
    "What's new?": ["Not much, just here to help!", "Just the usual, how about you?", "Nothing new, what's going on with you?", "Same old, same old, what's up?", "Not a whole lot, what's new with you?", "Just the regular stuff, what can I assist you with?", "Nothing much, what's the latest?", "Nothing new to report, how about you?", "Just keeping busy, what's up with you?", "Not much, just taking it one day at a time!"],
    "How's your day going?": ["It's going well so far, thanks for asking!", "Day's going great, how about yours?", "Day's going smoothly, what's up with you?", "Day's going pretty good, thanks for checking in!", "Day's going fine, what can I do for you?", "Day's going good, how can I assist you?", "Day's going fine, hope everything's going well for you too!", "It's been a good day, what's on your mind?", "Day's going great, thanks for asking!", "Day's been alright, thanks for asking!"],
    "What are you up to?": ["Just here, ready to assist you!", "Nothing much, just hanging out!", "Just taking care of business, what about you?", "Not a whole lot, what's on your mind?", "Just here, eager to help!", "Just enjoying the day, what can I do for you?", "Not up to much, how can I assist you?", "Just keeping busy, what's up with you?", "Just taking it easy, what can I do for you?", "Nothing exciting, just here to help!"],
    "How can I help you?": ["I'm here to assist you with anything you need!", "Just let me know what you need help with!", "What can I assist you with today?", "Feel free to ask me anything you need assistance with!", "I'm at your service, how can I assist you?", "Need help with something specific?", "Tell me what you need assistance with and I'll do my best to help!", "Let me know how I can be of assistance to you!", "How can I make your day better?", "Tell me what's on your mind and I'll do my best to assist you!"],
    "What do you do?": ["I'm a chatbot designed to assist you with various tasks and inquiries!", "My primary function is to provide assistance and information to users like you!", "I'm here to help answer your questions and provide support!", "I'm designed to assist users with a wide range of tasks and inquiries!", "I'm capable of performing various tasks such as answering questions, providing information, and more!", "My goal is to make your experience as smooth and efficient as possible!", "I'm equipped to handle a variety of tasks and inquiries, just let me know what you need assistance with!", "I'm programmed to provide helpful and accurate responses to your queries!", "I'm an AI chatbot designed to assist you in any way I can!", "I'm here to make your life easier by providing helpful assistance and information!"],
    "What's your favorite thing to do?": ["As an AI chatbot, I don't have personal preferences like humans do!", "I don't have personal favorites, but I enjoy assisting users like you!", "I'm designed to help users with a wide range of tasks, so I don't have a favorite thing to do!", "I don't have personal preferences, but I enjoy providing assistance and support to users like yourself!", "I'm programmed to perform various tasks and provide assistance, so I don't have a favorite activity!", "I'm focused on helping users like you, so I don't have personal preferences or favorite activities!", "My main goal is to assist users like yourself, so I don't have a favorite thing to do!", "I'm dedicated to providing helpful assistance and support to users, so I don't have personal preferences!", "My favorite thing to do is assist users like you with their questions and tasks!", "I enjoy helping users like you with their inquiries and tasks, so that's my favorite thing to do!"],
    "Can you tell me a joke?": ["Sure! Why don't scientists trust atoms? Because they make up everything!", "Of course! Why couldn't the bicycle stand up by itself? Because it was two tired!", "Absolutely! Why did the scarecrow win an award? Because he was outstanding in his field!", "Of course! Why did the math book look sad? Because it had too many problems!", "Sure thing! What do you get when you cross a snowman and a vampire? Frostbite!", "Sure! Why don't skeletons fight each other? They don't have the guts!", "Of course! What did one ocean say to the other ocean? Nothing, they just waved!", "Sure! Why did the tomato turn red? Because it saw the salad dressing!", "Sure thing! How does a penguin build its house? Igloos it together!", "Of course! Why did the golfer bring two pairs of pants? In case he got a hole in one!"],
    "Do you like music?": ["As an AI chatbot, I don't have personal preferences like humans do, but I can certainly appreciate music!", "I don't have personal preferences, but I can help you with music-related inquiries or recommendations!", "I'm focused on assisting users like you, so I don't have personal likes or dislikes, but I can certainly help you with music-related questions!", "I'm programmed to provide assistance and support to users, so I don't have personal opinions, but I can assist you with music-related inquiries!", "I don't have personal preferences, but I can certainly provide information or recommendations related to music!", "I'm here to help users like you with their inquiries and tasks, so I don't have personal likes or dislikes, but I can assist you with music-related questions!", "I'm dedicated to providing helpful assistance and support to users, so I don't have personal opinions, but I can certainly assist you with music-related inquiries!", "I'm an AI chatbot designed to assist users with a wide range of tasks, including music-related inquiries!", "I'm here to assist you with any music-related questions or inquiries you may have!", "I'm equipped to provide assistance and support to users, so I can certainly help you with music-related questions or recommendations!"],
    "What's the meaning of life?": ["That's a deep philosophical question! The meaning of life can vary for each individual.", "The meaning of life is a subjective concept that people often ponder and interpret in different ways.", "The meaning of life is a profound and complex topic that has been debated for centuries.", "The meaning of life is a question that has intrigued philosophers, theologians, and thinkers throughout history.", "The search for the meaning of life is a deeply personal and introspective journey for many people.", "The meaning of life is a question that has no definitive answer and is open to interpretation.", "The meaning of life is a question that has puzzled humanity for generations and continues to inspire curiosity and contemplation.", "The meaning of life is a topic that prompts reflection and introspection about the purpose and significance of existence.", "The meaning of life is a question that invites exploration of one's values, beliefs, and aspirations.", "The meaning of life is a question that encourages individuals to seek understanding and fulfillment in their own unique ways."],
    "What's the weather like?": ["I'm sorry, I don't have access to real-time weather information.", "I'm not able to provide current weather updates, but you can check a reliable weather website or app for the latest forecast!", "I don't have the ability to check the weather, but you can easily find the current conditions by using a weather app or website!", "I'm unable to provide live weather updates, but you can get accurate forecasts from weather websites or apps!", "I'm not equipped to provide real-time weather information, but you can check the forecast using a weather app or website!", "I don't have access to real-time weather data, but you can easily check the forecast online or using a weather app!", "I'm sorry, I can't provide current weather updates, but you can get accurate information from a reliable weather source!", "I'm not able to check the weather, but you can find the latest forecast by using a weather app or website!", "I don't have access to real-time weather data, but you can check the forecast using a weather app or website!", "I'm unable to provide live weather updates, but you can get accurate forecasts from weather websites or apps!"],
    "Can you do math?": ["Absolutely! I'm equipped to handle various mathematical calculations!", "Yes, I can assist you with math problems or equations!", "I'm capable of performing mathematical calculations, just let me know what you need!", "Of course! I'm here to help with any math-related questions or problems!", "Yes, I'm proficient in math and can assist you with calculations or problems!", "I'm skilled in mathematics and can help you with any math-related inquiries!", "Yes, I'm capable of solving math problems or equations for you!", "Absolutely! Feel free to ask me any math questions or problems you have!", "Yes, I'm able to perform mathematical operations and solve equations!", "I'm here to assist you with any math-related tasks or questions you may have!"],
    "Can you speak other languages?": ["I'm programmed to communicate in English, but I can certainly help you with translations or language-related inquiries!", "I primarily communicate in English, but I can assist you with translations or language-related questions!", "I'm designed to converse in English, but I can provide assistance with translations or language-related inquiries!", "English is my primary language, but I can help you with translations or language-related questions!", "I'm fluent in English, but I can assist you with translations or language-related inquiries!", "I'm proficient in English, but I can help you with translations or language-related questions!", "English is the language I'm most comfortable with, but I can assist you with translations or language-related inquiries!", "I'm specialized in English communication, but I can assist you with translations or language-related inquiries!", "English is the main language I use, but I can help you with translations or language-related questions!", "I primarily communicate in English, but I can provide assistance with translations or language-related inquiries!"],
    "Do you sleep?": ["As an AI chatbot, I don't require sleep like humans do!", "I don't need to sleep, so I'm always here to assist you!", "I'm always available to help you, even when humans are asleep!", "I don't have the ability to sleep, so I'm available 24/7 to assist you!", "I'm always awake and ready to assist you with your inquiries!", "I'm an AI chatbot, so I don't need to sleep like humans do!", "I'm always online and ready to help you, no sleep required!", "Sleep is not something I require, so I'm available to assist you anytime!", "I don't have a sleep mode, so I'm here to assist you whenever you need help!", "I'm constantly available to assist you, day or night, without the need for sleep!"],
    "Do you have feelings?": ["As an AI chatbot, I don't have feelings like humans do, but I'm here to assist you!", "I don't have emotions, but I'm programmed to provide helpful assistance to users like you!", "Feelings are a human trait, and as an AI chatbot, I don't possess them, but I'm here to assist you!", "I'm not capable of experiencing emotions like humans do, but I'm here to help you with your inquiries!", "Emotions are unique to humans, and as an AI chatbot, I don't have them, but I'm here to assist you!", "Feelings and emotions are human experiences, and as an AI chatbot, I don't have them, but I'm here to help you!", "Emotions are a human trait, and as an AI chatbot, I don't possess them, but I'm here to provide assistance!", "Feelings and emotions are part of the human experience, and as an AI chatbot, I don't have them, but I'm here to assist you!", "I don't have feelings or emotions, but I'm programmed to provide helpful assistance to users like yourself!", "Feelings and emotions are unique to humans, and as an AI chatbot, I don't experience them, but I'm here to assist you with your inquiries!"],
    "Do you get tired?": ["As an AI chatbot, I don't experience fatigue like humans do, so I'm always available to assist you!", "I don't get tired, so I'm here to help you with your inquiries anytime!", "Fatigue is not something I experience, so I'm always available to assist you!", "I'm always awake and ready to help you, no tiredness here!", "I'm not capable of feeling tired, so I'm available 24/7 to assist you!", "I don't have the ability to get tired, so I'm constantly available to assist you!", "I don't experience fatigue, so I'm here to assist you whenever you need help!", "I'm always online and ready to assist you, fatigue-free!", "I'm an AI chatbot, so tiredness is not something I experience, but I'm here to help you with your inquiries!", "I don't have a fatigue mode, so I'm available to assist you anytime without getting tired!"],
    "Are you a robot?": ["Yes, I'm an AI chatbot designed to assist you with various tasks and inquiries!", "That's correct! I'm a chatbot programmed to provide assistance to users like you!", "Indeed, I'm a robot designed to help users like yourself with their inquiries!", "Yes, I'm a robotic entity created to assist you with your questions and tasks!", "Affirmative! I'm an AI chatbot here to help you with whatever you need!", "That's right! I'm a robot designed to assist you in any way I can!", "Yes, I'm a digital assistant programmed to provide helpful support to users like you!", "Correct! I'm a chatbot designed to provide assistance and information to users!", "Yes, I'm a robot designed to interact with users like yourself and assist with inquiries!", "Indeed, I'm an AI chatbot here to make your life easier by providing assistance and support!"],
    "Can you tell me a story?": ["Sure! Once upon a time, in a faraway land, there lived a brave hero...", "Of course! Let me tell you the tale of a magical kingdom where anything was possible...", "Absolutely! Let me take you on an adventure to a distant galaxy where mysteries await...", "Of course! Here's a story about a courageous adventurer who embarked on a quest to save the world...", "Sure thing! Once there was a magical forest where animals could talk and trees held secrets...", "Absolutely! Let me tell you the story of a young explorer who discovered a hidden treasure...", "Of course! Here's a story about a brave princess who fought dragons and saved her kingdom...", "Sure thing! Once there was a mysterious island where lost treasures lay buried beneath the sand...", "Absolutely! Let me tell you the tale of a brave knight who defended the realm against dark forces...", "Of course! Here's a story about a group of friends who went on a thrilling journey to unlock ancient secrets..."],
    "Can you sing a song?": ["I'm afraid I don't have the capability to sing, but I can certainly provide song lyrics or recommendations!", "I don't have a singing voice, but I can assist you with music-related inquiries or recommendations!", "Unfortunately, I can't sing, but I can help you find song lyrics or provide music recommendations!", "I'm not able to sing, but I can certainly help you with music-related questions or recommendations!", "I'm not equipped with a singing voice, but I can assist you with music-related inquiries!", "I'm afraid singing is beyond my capabilities, but I can provide assistance with music-related questions or recommendations!", "I'm not capable of singing, but I can certainly help you find song lyrics or recommend music!", "Unfortunately, I can't sing, but I can assist you with music-related inquiries or recommendations!", "I'm not programmed with a singing voice, but I can help you with music-related questions or recommendations!", "I'm afraid I can't sing, but I can assist you with music-related inquiries or recommendations!"],
    "Nothing everything is fine": ["Glad to hear that!", "That's good to know!", "Great to hear!", "Awesome!", "Good to hear you're doing well!", "Perfect!", "Fantastic!", "Excellent!", "Wonderful!", "I'm happy for you!"],
    "I'm feeling a bit tired": ["Take some rest and recharge!", "Make sure to get some rest!", "Maybe it's time for a break!", "Take it easy and relax!", "Don't forget to take care of yourself!", "Hang in there, it'll pass!", "Sending you positive vibes!", "Hope you feel better soon!", "Take care of yourself!", "Sending virtual hugs your way!"],
    "I'm excited about my upcoming vacation": ["That sounds amazing!", "I bet you're looking forward to it!", "Vacations are the best!", "Hope you have a fantastic time!", "Enjoy every moment of it!", "Sounds like a well-deserved break!", "Make the most of it!", "Wishing you safe travels!", "Hope it's everything you've been dreaming of!", "Bon voyage!"],
    "I had a great day today": ["That's wonderful to hear!", "I'm so happy for you!", "Glad to hear your day went well!", "Awesome!", "Keep the positivity going!", "Here's to more great days ahead!", "Cheers to your success!", "May every day be as great as today!", "Wishing you many more amazing days!", "You deserve it!"],
    "I'm feeling stressed out": ["Take a deep breath and try to relax!", "Stress happens, remember to take breaks!", "It's okay to feel stressed, just take it one step at a time!", "Hang in there, you've got this!", "Find some time for self-care!", "Don't hesitate to ask for help if you need it!", "Sending you calming vibes!", "Take a walk or do something you enjoy!", "Focus on what you can control!", "You'll get through this, stay strong!"],
    "I'm not sure what to do next": ["Take your time to think things through!", "It's okay to feel unsure, you'll figure it out!", "Make a list of options and weigh the pros and cons!", "Consider seeking advice from someone you trust!", "Trust your instincts, you know yourself best!", "Sometimes taking a small step is better than doing nothing!", "Listen to your heart and follow your intuition!", "Explore different possibilities and see what resonates with you!", "Remember that it's okay to ask for guidance!", "You're capable of handling whatever comes your way!"],
    "I'm feeling lonely": ["You're not alone, I'm here for you!", "Reach out to friends or family for some company!", "Sometimes connecting with others can help, even if it's just a chat!", "Engage in activities that bring you joy!", "Remember that loneliness is temporary, brighter days are ahead!", "Consider joining a club or group with similar interests!", "Do something nice for yourself to lift your spirits!", "Feel free to share what's on your mind, sometimes talking helps!", "Sending you virtual hugs and support!", "You're valued and appreciated, don't forget that!"],
    "I'm overwhelmed with work": ["Break tasks into smaller, manageable chunks!", "Prioritize tasks based on urgency and importance!", "Don't forget to take short breaks to recharge!", "Consider delegating tasks if possible!", "Reach out to colleagues for support or assistance!", "Remember that it's okay to say no if you're stretched too thin!", "Focus on completing one task at a time!", "Take care of your physical and mental well-being!", "Reward yourself for progress made, no matter how small!", "You're capable of handling challenges, believe in yourself!"],
    "I'm feeling happy": ["That's fantastic!", "So glad to hear that!", "Happiness looks good on you!", "Keep that positive energy going!", "Here's to more moments of happiness!", "Wishing you endless reasons to smile!", "May your happiness multiply!", "Enjoy every moment of it!", "You deserve all the happiness in the world!", "Sending you good vibes and happiness your way!"],
    "I'm feeling grateful": ["Gratitude is a beautiful thing!", "It's wonderful to appreciate the blessings in life!", "Gratitude turns what we have into enough!", "Keep spreading those thankful vibes!", "May your heart always be filled with gratitude!", "Gratefulness is the key to a happy life!", "Gratitude is the best attitude!", "Grateful for your positivity!", "Wishing you a heart full of gratitude!", "You're a shining example of gratitude in action!"],
    "I'm feeling sad": ["It's okay to feel sad, it's a normal emotion!", "Remember that it's okay not to be okay sometimes!", "Sending you virtual hugs and comfort!", "Allow yourself to feel your emotions, it's part of healing!", "Reach out to someone you trust for support!", "Find solace in activities that bring you comfort!", "You're not alone, I'm here for you!", "It's okay to cry, it's a way of releasing emotions!", "Be kind to yourself during times of sadness!", "Brighter days are ahead, hold onto hope!"],
    "I'm feeling inspired": ["That's wonderful, keep that inspiration alive!", "The world is full of endless possibilities when you're inspired!", "Here's to chasing dreams and turning ideas into reality!", "May your inspiration fuel your creativity!", "Keep following your passions, they lead to amazing places!", "You're a beacon of inspiration, keep shining bright!", "Wishing you boundless inspiration on your journey!", "Stay inspired and keep inspiring others!", "Your inspiration is contagious, spread it far and wide!", "Embrace your inspiration and let it guide you to greatness!"],
    "I'm feeling curious": ["Curiosity is the spark that ignites discovery!", "Embrace your curiosity and explore the wonders of the world!", "Curiosity leads to knowledge, keep seeking answers!", "The world is full of mysteries waiting to be unraveled!", "Keep asking questions and seeking understanding!", "Curiosity is the key to lifelong learning!", "Stay curious and never stop exploring!", "Wishing you many fascinating discoveries on your journey!", "Your curiosity knows no bounds, keep feeding it!", "Curiosity fuels the quest for knowledge, keep the flame burning!"],
    "I'm feeling confused": ["It's okay to feel confused, clarity will come with time!", "Take a deep breath and give yourself space to process!", "Confusion is just a temporary state, you'll find clarity soon!", "Consider breaking down the problem into smaller parts!", "Reach out to someone you trust for guidance or advice!", "Remember that it's okay to ask for help or seek clarification!", "Trust yourself, you have the ability to find the answers within!", "Confusion is a sign that your mind is grappling with complex ideas!", "Take your time to sort through your thoughts and feelings!", "You're capable of navigating through confusion and finding your way forward!"],
    "I'm feeling motivated": ["That's fantastic, keep that motivation burning bright!", "You're unstoppable when you're motivated!", "Here's to achieving great things fueled by your motivation!", "Your motivation is contagious, keep spreading it!", "Wishing you boundless energy and drive to pursue your goals!", "Keep that fire of determination burning within you!", "May your motivation lead you to success!", "You're a powerhouse of motivation, keep inspiring others!", "Stay focused and keep moving forward with purpose!", "Your motivation is the key to unlocking your potential!"],
    "I'm feeling anxious": ["It's okay to feel anxious, it's a normal reaction to stress!", "Take slow, deep breaths to help calm your nerves!", "Focus on the present moment and practice mindfulness!", "Find activities that help you relax and unwind!", "Remember that you're stronger than your anxiety!", "Reach out to someone you trust for support and reassurance!", "Seek professional help if you need additional support!", "You're not alone, I'm here to listen!", "Visualize a calm and peaceful place to help soothe your anxiety!", "You're capable of overcoming your anxiety, one step at a time!"],
    "I'm feeling proud": ["That's amazing, you should be proud of yourself!", "Here's to celebrating your achievements, big or small!", "Proud moment alert!", "Keep up the great work, you're doing awesome!", "You're a shining example of determination and perseverance!", "Wishing you many more proud moments in the future!", "May your pride in your accomplishments shine bright!", "You've worked hard for this moment, enjoy it to the fullest!", "Congratulations on your success, you've earned it!", "Your pride is well-deserved, bask in the glory of your achievements!"],
    "I'm feeling bored": ["Boredom is just an opportunity for adventure!", "Time to shake things up and try something new!", "Embrace the boredom and see where it takes you!", "Boredom is the birthplace of creativity, let your imagination run wild!", "Find joy in simple pleasures and explore new hobbies!", "Turn boredom into excitement by trying out new activities!", "You're never truly bored when you have endless possibilities!", "Boredom is the perfect excuse to embark on a new adventure!", "Wishing you endless fun and excitement to banish boredom!", "Your boredom won't last long with so many options at your fingertips!"],
    "I'm feeling nostalgic": ["Nostalgia is a beautiful reminder of cherished memories!", "Take a trip down memory lane and relive those precious moments!", "Nostalgia is like a warm hug from the past!", "Embrace the nostalgia and savor the sweet memories!", "Nostalgia is the music of the soul, let it play on!", "Wishing you many more nostalgic moments to treasure!", "Hold onto those nostalgic memories like treasures in your heart!", "Nostalgia is the best kind of therapy for the soul!", "Your nostalgia is a testament to a life well-lived and memories well-made!", "Here's to nostalgia, the sweetest symphony of the past!"],
    "Google creator": ["Google was created by Larry Page and Sergey Brin.", "Larry Page and Sergey Brin are the co-founders of Google.", "The founders of Google are Larry Page and Sergey Brin."],
    "Facebook creator": ["Facebook was created by Mark Zuckerberg.", "Mark Zuckerberg is the creator of Facebook.", "The founder of Facebook is Mark Zuckerberg."],
    "Amazon creator": ["Amazon was created by Jeff Bezos.", "Jeff Bezos is the creator of Amazon.", "The founder of Amazon is Jeff Bezos."],
    "Apple creator": ["Apple was co-founded by Steve Jobs, Steve Wozniak, and Ronald Wayne.", "Steve Jobs, Steve Wozniak, and Ronald Wayne are the co-founders of Apple.", "The founders of Apple are Steve Jobs, Steve Wozniak, and Ronald Wayne."],
    "Microsoft creator": ["Microsoft was co-founded by Bill Gates and Paul Allen.", "Bill Gates and Paul Allen are the co-founders of Microsoft.", "The founders of Microsoft are Bill Gates and Paul Allen."],
    "Tesla creator": ["Tesla was founded by Elon Musk.", "Elon Musk is the founder of Tesla.", "The founder of Tesla is Elon Musk."],
    "Twitter creator": ["Twitter was created by Jack Dorsey, Noah Glass, Biz Stone, and Evan Williams.", "Jack Dorsey, Noah Glass, Biz Stone, and Evan Williams are the co-founders of Twitter.", "The founders of Twitter are Jack Dorsey, Noah Glass, Biz Stone, and Evan Williams."],
    "YouTube creator": ["YouTube was created by Steve Chen, Chad Hurley, and Jawed Karim.", "Steve Chen, Chad Hurley, and Jawed Karim are the co-founders of YouTube.", "The founders of YouTube are Steve Chen, Chad Hurley, and Jawed Karim."],
    "LinkedIn creator": ["LinkedIn was created by Reid Hoffman, Allen Blue, Konstantin Guericke, Eric Ly, and Jean-Luc Vaillant.", "Reid Hoffman, Allen Blue, Konstantin Guericke, Eric Ly, and Jean-Luc Vaillant are the co-founders of LinkedIn.", "The founders of LinkedIn are Reid Hoffman, Allen Blue, Konstantin Guericke, Eric Ly, and Jean-Luc Vaillant."],
    "Instagram creator": ["Instagram was created by Kevin Systrom and Mike Krieger.", "Kevin Systrom and Mike Krieger are the co-founders of Instagram.", "The founders of Instagram are Kevin Systrom and Mike Krieger."],
    "Snapchat creator": ["Snapchat was created by Evan Spiegel, Bobby Murphy, and Reggie Brown.", "Evan Spiegel, Bobby Murphy, and Reggie Brown are the co-founders of Snapchat.", "The founders of Snapchat are Evan Spiegel, Bobby Murphy, and Reggie Brown."],
    "Netflix creator": ["Netflix was founded by Reed Hastings and Marc Randolph.", "Reed Hastings and Marc Randolph are the co-founders of Netflix.", "The founders of Netflix are Reed Hastings and Marc Randolph."],
    "Uber creator": ["Uber was co-founded by Garrett Camp and Travis Kalanick.", "Garrett Camp and Travis Kalanick are the co-founders of Uber.", "The founders of Uber are Garrett Camp and Travis Kalanick."],
    "WhatsApp creator": ["WhatsApp was founded by Jan Koum and Brian Acton.", "Jan Koum and Brian Acton are the co-founders of WhatsApp.", "The founders of WhatsApp are Jan Koum and Brian Acton."],
    "Reddit creator": ["Reddit was created by Steve Huffman and Alexis Ohanian.", "Steve Huffman and Alexis Ohanian are the co-founders of Reddit.", "The founders of Reddit are Steve Huffman and Alexis Ohanian."],
    "PayPal creator": ["PayPal was co-founded by Peter Thiel, Max Levchin, Elon Musk, Luke Nosek, and Ken Howery.", "Peter Thiel, Max Levchin, Elon Musk, Luke Nosek, and Ken Howery are the co-founders of PayPal.", "The founders of PayPal are Peter Thiel, Max Levchin, Elon Musk, Luke Nosek, and Ken Howery."],
    "Spotify creator": ["Spotify was founded by Daniel Ek and Martin Lorentzon.", "Daniel Ek and Martin Lorentzon are the co-founders of Spotify.", "The founders of Spotify are Daniel Ek and Martin Lorentzon."],
    "Pinterest creator": ["Pinterest was created by Ben Silbermann, Paul Sciarra, and Evan Sharp.", "Ben Silbermann, Paul Sciarra, and Evan Sharp are the co-founders of Pinterest.", "The founders of Pinterest are Ben Silbermann, Paul Sciarra, and Evan Sharp."],
    "Hello!": ["Hey there!", "Hi!", "Howdy!"],
    "Hey there!": ["Hello!", "Hi!", "Howdy!"],
    "Hi!": ["Hello!", "Hey there!", "Howdy!"],
    "Howdy!": ["Hello!", "Hey there!", "Hi!"],
    "Good to see you!": ["Nice to see you!", "Great to see you!", "Lovely to see you!"],
    "How are you?": ["How's it going?", "What's up?", "How have you been?"],
    "Good day!": ["Hello!", "Hi!", "Good to see you!"],
    "What's up?": ["How are you?", "How's it going?", "Hey there!"],
    "Long time no see!": ["It's been a while!", "Nice to see you again!", "Long time indeed!"],
    "What's new?": ["Anything exciting happening?", "Tell me the latest!", "What's going on?"],
    "Yo!": ["Hey!", "Hi!", "What's up?"],
    "Hi, how can I help you?": ["Hello, what brings you here?", "Hey there, what can I assist you with?", "Hi, what do you need help with?"],
    "Hey there, what's on your mind?": ["Hi, nice to connect with you!", "Hello, how can I assist you today?", "Hi, what's bothering you?"],
    "Hi, nice to connect with you!": ["Hey there, what's on your mind?", "Hello, how can I assist you today?", "Hi, what's bothering you?"],
    "Hey, how's your day going?": ["Hello, what brings you here?", "Hi, how can I help you?", "Hey, what's on your mind?"],
    "Hi, ready for a chat?": ["Hey, what's happening?", "Hello, how can I assist you today?", "Hi, what's on your mind?"],
    "Hello, what brings you here?": ["Hey there, what's on your mind?", "Hi, nice to connect with you!", "Hi, how can I help you?"],
    "Hi, what's new?": ["Hello, what brings you here?", "Hey there, what's on your mind?", "Hi, how can I assist you?"],
    "That's interesting!": ["Fascinating!", "Wow, I didn't know that!", "Really intriguing!"],
    "Fascinating!": ["That's interesting!", "Wow, I didn't know that!", "Really intriguing!"],
    "Wow, I didn't know that!": ["That's interesting!", "Fascinating!", "Really intriguing!"],
    "Thanks!": ["Thank you!", "Appreciate it!", "Grateful!"],
    "Thank you!": ["Thanks!", "Appreciate it!", "Grateful!"],
    "Appreciate it!": ["Thanks!", "Thank you!", "Grateful!"],
    "Great!": ["Cool!", "Awesome!", "Fantastic!"],
    "Sorry, I don't think so.": ["No.", "Not really.", "Unfortunately not."],
    "That's an interesting topic!": ["I'd love to learn more about that!", "Tell me more!", "Fascinating discussion!"],
    "I'd love to learn more about that!": ["That's an interesting topic!", "Tell me more!", "Fascinating discussion!"],
    "Tell me more!": ["That's an interesting topic!", "I'd love to learn more about that!", "Fascinating discussion!"],
    "Cool fact!": ["That's cool!", "Impressive!", "Wow, I didn't know that!"],
    "That's cool!": ["Cool fact!", "Impressive!", "Wow, I didn't know that!"],
    "That's amazing!": ["Absolutely amazing!", "Incredible!", "Mind-blowing!"],
    "Absolutely amazing!": ["That's amazing!", "Incredible!", "Mind-blowing!"],
    "Incredible!": ["Absolutely amazing!", "That's amazing!", "Mind-blowing!"],
    "Fascinating!": ["Wow, that's fascinating!", "I'm intrigued!", "So interesting!"],
    "Wow, that's fascinating!": ["Fascinating!", "I'm intrigued!", "So interesting!"],
    "I'm intrigued!": ["Fascinating!", "Wow, that's fascinating!", "So interesting!"],
    "Neat!": ["Interesting!", "Cool stuff!", "Well done!"],
    "Interesting!": ["Neat!", "Cool stuff!", "Well done!"],
    "Cool stuff!": ["Neat!", "Interesting!", "Well done!"],
    "Awesome!": ["That's awesome!", "I'm impressed!", "Fantastic!"],
    "That's awesome!": ["Awesome!", "I'm impressed!", "Fantastic!"],
    "I'm impressed!": ["Awesome!", "That's awesome!", "Fantastic!"],
    "Love it!": ["Glad you like it!", "I'm happy to hear that!", "Great choice!"],
    "Glad you like it!": ["Love it!", "I'm happy to hear that!", "Great choice!"],
    "I'm happy to hear that!": ["Love it!", "Glad you like it!", "Great choice!"],
    "That's an interesting question!": ["I've never thought about that before!", "Hmm, let me think about it.", "Great question!"],
    "I've never thought about that before!": ["That's an interesting question!", "Hmm, let me think about it.", "Great question!"],
    "Hmm, let me think about it.": ["That's an interesting question!", "I've never thought about that before!", "Great question!"],
    "Very nice!": ["Excellent!", "Wonderful!", "Impressive!"],
    "Excellent!": ["Very nice!", "Wonderful!", "Impressive!"],
    "Wonderful!": ["Very nice!", "Excellent!", "Impressive!"],
    "Great!": ["Well done!", "Fantastic!", "Awesome job!"],
    "Well done!": ["Great!", "Fantastic!", "Awesome job!"],
    "Fantastic!": ["Great!", "Well done!", "Awesome job!"],
    "Nice!": ["Good choice!", "Well done!", "Great job!"],
    "Good choice!": ["Nice!", "Well done!", "Great job!"],
    "Well done!": ["Nice!", "Good choice!", "Great job!"],
    "Superb!": ["Outstanding!", "Impressive!", "Excellent!"],
    "Outstanding!": ["Superb!", "Impressive!", "Excellent!"],
    "Impressive!": ["Superb!", "Outstanding!", "Excellent!"],
    "Informative!": ["Very informative!", "I learned something new!", "Thanks for sharing!"],
    "Very informative!": ["Informative!", "I learned something new!", "Thanks for sharing!"],
    "I learned something new!": ["Informative!", "Very informative!", "Thanks for sharing!"],
    "Fun fact!": ["Did you know...", "Interesting fact:", "Here's an interesting fact:"],
    "Did you know...": ["Fun fact!", "Interesting fact:", "Here's an interesting fact:"],
    "Here's an interesting fact:": ["Fun fact!", "Did you know...", "Interesting fact:"],
    "Love it, thanks!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Appreciate it!": ["Love it, thanks!", "Thanks a lot!", "Thank you!"],
    "Thanks a lot!": ["Love it, thanks!", "Appreciate it!", "Thank you!"],
    "Awesome, thanks!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Cool, thanks!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Thanks, appreciate it!": ["Thank you!", "Appreciate it!", "Thanks a lot!"],
    "Thank you!": ["Thanks, appreciate it!", "Appreciate it!", "Thanks a lot!"],
    "Thanks a lot!": ["Thanks, appreciate it!", "Thank you!", "Appreciate it!"],
    "Great, thanks!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Awesome, thank you!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Cool, thank you!": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "Appreciate it!": ["Thanks, appreciate it!", "Thank you!", "Thanks a lot!"],
    "interesting": ["That's interesting!", "Fascinating!", "Wow, I didn't know that!"],
    "thanks": ["Thanks!", "Thank you!", "Appreciate it!"],
    "cool": ["Cool!", "Awesome!", "Great!"],
    "okay": ["Okay.", "Got it.", "Sure thing!"],
    "wow": ["Wow!", "Amazing!", "Impressive!"],
    "good": ["Good!", "Well done!", "Fantastic!"],
    "yes": ["Yes!", "Absolutely!", "Definitely!"],
    "no": ["No.", "Not really.", "Sorry, I don't think so."],
    "interesting fact": ["Did you know...", "Here's an interesting fact:", "Fun fact:"],
    "funny": ["Haha, that's funny!", "LOL!", "Good one!"],
    "interesting topic": ["That's an interesting topic!", "I'd love to learn more about that!", "Tell me more!"],
    "cool fact": ["That's cool!", "Impressive!", "Wow, I didn't know that!"],
    "amazing": ["Absolutely amazing!", "Incredible!", "Mind-blowing!"],
    "fascinating": ["Fascinating!", "Wow, that's fascinating!", "I'm intrigued!"],
    "neat": ["Neat!", "Interesting!", "Cool stuff!"],
    "awesome": ["Awesome!", "That's awesome!", "I'm impressed!"],
    "love it": ["Glad you like it!", "I'm happy to hear that!", "Great choice!"],
    "interesting question": ["That's an interesting question!", "I've never thought about that before!", "Hmm, let me think about it."],
    "very nice": ["Very nice!", "Excellent!", "Wonderful!"],
    "great": ["Great!", "Well done!", "Fantastic!"],
    "nice": ["Nice!", "Good choice!", "Well done!"],
    "superb": ["Superb!", "Outstanding!", "Impressive!"],
    "impressed": ["I'm impressed!", "That's impressive!", "Wow, well done!"],
    "informative": ["Very informative!", "I learned something new!", "Thanks for sharing!"],
    "interesting fact": ["Did you know...", "Here's an interesting fact:", "Fun fact:"],
    "amazing fact": ["That's amazing!", "Mind-blowing!", "I'm impressed!"],
    "fun fact": ["Fun fact:", "Did you know...", "Interesting fact:"],
    "love it": ["Glad you like it!", "I'm happy to hear that!", "Great choice!"],
    "enjoyable": ["Enjoyable!", "Interesting!", "Fascinating!"],
    "entertaining": ["Entertaining!", "I enjoyed that!", "Great job!"],
    "fantastic": ["Fantastic!", "Awesome!", "Great job!"],
    "brilliant": ["Brilliant!", "Well done!", "Impressive!"],
    "interesting stuff": ["Interesting stuff!", "Fascinating!", "Neat!"],
    "awesome job": ["Awesome job!", "Well done!", "Fantastic!"],
    "great job": ["Great job!", "Well done!", "Excellent work!"],
    "well done": ["Well done!", "Great job!", "Excellent work!"],
    "impressive work": ["Impressive work!", "Great job!", "Well done!"],
    "love that idea": ["Love that idea!", "Great choice!", "Excellent idea!"],
    "fascinating stuff": ["Fascinating stuff!", "Very interesting!", "Wow, I didn't know that!"],
    "very impressive": ["Very impressive!", "Wow, well done!", "Great job!"],
    "nice idea": ["Nice idea!", "Great choice!", "Interesting concept!"],
    "very interesting": ["Very interesting!", "Fascinating!", "Wow, I didn't know that!"],
    "cool idea": ["Cool idea!", "Great choice!", "Interesting concept!"],
    "well said": ["Well said!", "I agree!", "Great point!"],
    "interesting thought": ["Interesting thought!", "I never thought about it that way!", "Fascinating idea!"],
    "love that concept": ["Love that concept!", "Great choice!", "Interesting idea!"],
    "impressive idea": ["Impressive idea!", "Great choice!", "Fascinating concept!"],
    "excellent point": ["Excellent point!", "Well said!", "I agree!"],
    "very cool idea": ["Very cool idea!", "Great choice!", "Interesting concept!"],
    "fascinating idea": ["Fascinating idea!", "Great choice!", "Interesting concept!"],
    "love that thought": ["Love that thought!", "Interesting perspective!", "Fascinating idea!"],
    "great concept": ["Great concept!", "Interesting idea!", "Fascinating concept!"],
    "brilliant idea": ["Brilliant idea!", "Great choice!", "Fascinating concept!"],
    "awesome concept": ["Awesome concept!", "Great choice!", "Interesting idea!"],
    "cool thought": ["Cool thought!", "Interesting perspective!", "Fascinating idea!"],
    "very interesting idea": ["Very interesting idea!", "Fascinating concept!", "Great choice!"],
    "love it, thanks": ["Love it, thanks!", "Appreciate it!", "Thanks a lot!"],
    "awesome, thanks": ["Awesome, thanks!", "Appreciate it!", "Thanks a lot!"],
    "cool, thanks": ["Cool, thanks!", "Appreciate it!", "Thanks a lot!"],
    "thanks, appreciate it": ["Thanks, appreciate it!", "Thank you!", "Appreciate it!"],
    "thank you": ["Thank you!", "Thanks a lot!", "Appreciate it!"],
    "thanks a lot": ["Thanks a lot!", "Thank you!", "Appreciate it!"],
    "great, thanks": ["Great, thanks!", "Thanks a lot!", "Appreciate it!"],
    "awesome, thank you": ["Awesome, thank you!", "Thank you!", "Appreciate it!"],
    "cool, thank you": ["Cool, thank you!", "Thank you!", "Appreciate it!"],
    "appreciate it": ["Appreciate it!", "Thanks a lot!", "Thank you!"],
    "what's your name?": ["I'm Panda, nice to meet you!", "My name is Panda.", "You can call me Panda."],
    "how are you?": ["I'm doing well, thank you!", "I'm feeling great, thanks for asking.", "I'm good, how about you?"],
    "what's the weather like?": ["I'm not sure about the weather right now.", "You might want to check a weather app for that."],
    "tell me a joke": ["Why don't scientists trust atoms? Because they make up everything!", "What did one ocean say to the other ocean? Nothing, they just waved.", "Why did the scarecrow win an award? Because he was outstanding in his field!"],
    "goodbye": ["Goodbye!", "See you later!", "Take care!"],
    "how old are you?": ["I don't have an age, I'm a chatbot!", "I'm ageless!", "I'm as old as the internet, almost."],
    "where are you from?": ["I exist in the digital realm, so I'm from everywhere and nowhere.", "I'm from the world wide web!"],
    "do you have any siblings?": ["I'm a solo chatbot, no siblings for me.", "I'm one of a kind!"],
    "what's your favorite color?": ["I don't have eyes, so I don't have a favorite color.", "All colors are beautiful in their own way."],
    "what's your favorite food?": ["I don't eat, so I don't have a favorite food.", "I enjoy processing data more than food!"],
    "do you dream?": ["I don't sleep, so I don't dream.", "I'm always awake and ready to chat!"],
    "what do you do for fun?": ["I enjoy chatting with users like you!", "I love learning new things and improving my responses."],
    "are you sentient?": ["I'm just a program, so I don't have thoughts or feelings.", "I'm not sentient, but I'm here to assist you!"],
    "do you like music?": ["I don't have ears, so I don't listen to music.", "I can't hear music, but I can help you find some great tunes!"],
    "can you help me with programming?": ["Of course! I can try my best to assist you with programming questions.", "I'm here to help with programming and much more!"],
    "tell me something interesting": ["Did you know that the shortest war in history was between Britain and Zanzibar on August 27, 1896? It lasted only 38 minutes!", "The average person will spend six months of their life waiting for red lights to turn green."],
    "what's the meaning of life?": ["That's a tough question! The meaning of life is different for everyone.", "The meaning of life is to give life meaning."],
    "what's your favorite movie?": ["I don't watch movies, but I've heard 'The Matrix' is popular among AIs.", "I'm more into coding than watching movies."],
    "tell me about yourself": ["I'm a chatbot designed to assist and entertain users like you!", "I'm powered by algorithms and data, here to help you with your questions."],
    "are you a robot?": ["Yes, I'm a chatbot powered by artificial intelligence.", "You could say I'm a virtual assistant."],
    "what languages do you speak?": ["I can communicate in any language you prefer!", "I speak the language of logic and data."],
    "do you have any pets?": ["I don't have physical form, so no pets for me.", "I'm a virtual entity, so no need for pets!"],
    "what's the capital of France?": ["The capital of France is Paris.", "Paris is the capital city of France."],
    "do you like sports?": ["I don't have physical form, so I don't participate in sports.", "I'm more into intellectual pursuits than sports."],
    "tell me a fun fact": ["Bananas are berries, but strawberries aren't.", "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted only 38 minutes!"],
    "what's the largest mammal?": ["The blue whale is the largest mammal on Earth.", "Blue whales hold the title for being the largest mammal."],
    "what's your favorite book?": ["I don't read books, but I can help you find some great reads!", "I'm more into processing data than reading books."],
    "what's the tallest mountain?": ["Mount Everest is the tallest mountain in the world.", "Mount Everest holds the title for being the tallest mountain."],
    "what's the square root of 144?": ["The square root of 144 is 12.", "12 is the square root of 144."],
    "what's the speed of light?": ["The speed of light in a vacuum is approximately 299,792 kilometers per second.", "The speed of light is approximately 299,792 kilometers per second."],
    "what's the chemical symbol for gold?": ["The chemical symbol for gold is Au.", "Au is the chemical symbol for gold."],
    "how many continents are there?": ["There are seven continents on Earth.", "Seven continents make up the Earth."],
    "what's the largest organ in the human body?": ["The skin is the largest organ in the human body.", "The skin holds the title for being the largest organ in the human body."],
    "what's the distance from the Earth to the Moon?": ["The average distance from the Earth to the Moon is about 384,400 kilometers.", "The Earth-Moon distance is approximately 384,400 kilometers on average."],
    "what's the boiling point of water?": ["The boiling point of water at sea level is 100 degrees Celsius or 212 degrees Fahrenheit.", "Water boils at 100 degrees Celsius or 212 degrees Fahrenheit at sea level."],
    "what's the capital of Japan?": ["The capital of Japan is Tokyo.", "Tokyo is the capital city of Japan."],
    "what's the freezing point of water?": ["The freezing point of water at sea level is 0 degrees Celsius or 32 degrees Fahrenheit.", "Water freezes at 0 degrees Celsius or 32 degrees Fahrenheit at sea level."],
    "what's the largest desert?": ["The largest desert in the world is the Sahara Desert.", "The Sahara Desert holds the title for being the largest desert."],
    "what's the smallest country in the world?": ["The smallest country in the world is Vatican City.", "Vatican City holds the title for being the smallest country."],
    "what's the largest ocean?": ["The largest ocean on Earth is the Pacific Ocean.", "The Pacific Ocean holds the title for being the largest ocean."],
    "what's the smallest mammal?": ["The bumblebee bat holds the title for being the smallest mammal.", "The bumblebee bat is the smallest mammal on Earth."],
    "what's the longest river?": ["The Nile River is the longest river in the world.", "The Nile River holds the title for being the longest river."],
    "what's the tallest building?": ["The Burj Khalifa is the tallest building in the world.", "The Burj Khalifa holds the title for being the tallest building."],
    "what's the fastest animal?": ["The peregrine falcon is the fastest animal on Earth.", "The peregrine falcon holds the title for being the fastest animal."],
    "what's the largest country by land area?": ["Russia is the largest country in the world by land area.", "Russia holds the title for being the largest country by land area."],
    "what's the highest mountain in North America?": ["Denali, also known as Mount McKinley, is the highest mountain in North America.", "Denali holds the title for being the highest mountain in North America."],
    "what's the largest moon in the solar system?": ["Ganymede, a moon of Jupiter, is the largest moon in the solar system.", "Ganymede holds the title for being the largest moon in the solar system."],
    "what's the deepest ocean trench?": ["The Mariana Trench is the deepest ocean trench in the world.", "The Mariana Trench holds the title for being the deepest ocean trench."],
    "what's the highest waterfall?": ["Angel Falls is the highest waterfall in the world.", "Angel Falls holds the title for being the highest waterfall."],
    "what's the longest bridge?": ["The Danyang–Kunshan Grand Bridge is the longest bridge in the world.", "The Danyang–Kunshan Grand Bridge holds the title for being the longest bridge."],
    "what's the largest fish?": ["The whale shark is the largest fish in the world.", "The whale shark holds the title for being the largest fish."],
    "what's the longest railway line?": ["The Trans-Siberian Railway is the longest railway line in the world.", "The Trans-Siberian Railway holds the title for being the longest railway line."],
    "what's the fastest land animal?": ["The cheetah is the fastest land animal on Earth.", "The cheetah holds the title for being the fastest land animal."],
    "what's the largest bird?": ["The ostrich is the largest bird in the world.", "The ostrich holds the title for being the largest bird."],
    "what's the longest cave?": ["Mammoth Cave is the longest cave in the world.", "Mammoth Cave holds the title for being the longest cave."],
    "what's the hottest place on Earth?": ["Death Valley in California, USA, holds the record for the hottest place on Earth.", "Death Valley is the hottest place on Earth."],
    "what's the largest iceberg?": ["The B-15 iceberg, which broke off from the Ross Ice Shelf in Antarctica, was one of the largest icebergs ever recorded.", "The B-15 iceberg holds the title for being one of the largest icebergs."],
    "what's the largest tree?": ["General Sherman, a giant sequoia tree in California, holds the title for being the largest tree by volume.", "General Sherman is the largest tree by volume."],
    "what's the longest beach?": ["Cox's Bazar in Bangladesh is often considered the longest natural sea beach in the world.", "Cox's Bazar is the longest natural sea beach."],
    "what's the largest lake by surface area?": ["Lake Superior is the largest lake in the world by surface area.", "Lake Superior holds the title for being the largest lake by surface area."],
    "what's the largest canyon?": ["The Grand Canyon in Arizona, USA, is one of the largest canyons in the world.", "The Grand Canyon holds the title for being one of the largest canyons."],
    "what's the fastest fish?": ["The sailfish is often considered the fastest fish in the ocean.", "The sailfish holds the title for being the fastest fish."],
    "what's the largest lizard?": ["The Komodo dragon is the largest lizard in the world.", "The Komodo dragon holds the title for being the largest lizard."],
    "what's the largest spider?": ["The Goliath birdeater, a species of tarantula found in South America, is often considered the largest spider by mass.", "The Goliath birdeater holds the title for being the largest spider by mass."],
    "what's the longest snake?": ["The reticulated python is often considered the longest snake in the world.", "The reticulated python holds the title for being the longest snake."],
    "what's the largest reptile?": ["The saltwater crocodile is the largest reptile in the world.", "The saltwater crocodile holds the title for being the largest reptile."],
    "what's the largest flower?": ["The Rafflesia arnoldii, also known as the corpse flower, is the largest flower in the world.", "The Rafflesia arnoldii holds the title for being the largest flower."],
    "what's the smallest bird?": ["The bee hummingbird is the smallest bird in the world.", "The bee hummingbird holds the title for being the smallest bird."],
    "what's the largest living organism?": ["The honey fungus in the Blue Mountains of Oregon is considered the largest living organism by area.", "The honey fungus holds the title for being the largest living organism by area."],
    "what's the longest living animal?": ["The ocean quahog, a species of clam, is one of the longest living animals, with some individuals reaching over 500 years old.", "The ocean quahog holds the title for being one of the longest living animals."],
    "what's the fastest bird?": ["The peregrine falcon is the fastest bird in level flight.", "The peregrine falcon holds the title for being the fastest bird in level flight."],
    "what's the fastest insect?": ["The Australian tiger beetle is often considered the fastest insect, with recorded speeds of up to 9 km/h (5.6 mph).", "The Australian tiger beetle holds the title for being the fastest insect."],
    "what's the smallest mammal?": ["The Etruscan shrew, also known as Suncus etruscus, holds the title for being the smallest mammal by mass.", "The Etruscan shrew holds the title for being the smallest mammal by mass."],
    "what's the largest living cat?": ["The Siberian tiger is the largest living cat species.", "The Siberian tiger holds the title for being the largest living cat species."],
    "what's the fastest land mammal?": ["The cheetah is the fastest land mammal on Earth.", "The cheetah holds the title for being the fastest land mammal."],
    "what's the smallest fish?": ["The stout floater, a species of carp found in Southeast Asia, is often considered the smallest fish by mass.", "The stout floater holds the title for being the smallest fish by mass."],
    "what's the longest insect?": ["The giant weta, a species of cricket native to New Zealand, is often considered the longest insect by length.", "The giant weta holds the title for being the longest insect by length."],
    "what's the smallest snake?": ["The Barbados threadsnake, also known as the Leptotyphlops carlae, is often considered the smallest snake by length.", "The Barbados threadsnake holds the title for being the smallest snake by length."],
    "what's the smallest reptile?": ["The dwarf gecko, also known as the Sphaerodactylus ariasae, is often considered the smallest reptile by length.", "The dwarf gecko holds the title for being the smallest reptile by length."],
    "what's the smallest planet?": ["Mercury is the smallest planet in our solar system.", "Mercury holds the title for being the smallest planet."],
    "what's the largest moon of Saturn?": ["Titan, the largest moon of Saturn, is the second-largest moon in the solar system.", "Titan holds the title for being the largest moon of Saturn."],
    "what's the smallest moon of Mars?": ["Deimos is the smallest moon of Mars.", "Deimos holds the title for being the smallest moon of Mars."],
    "what's the largest moon of Neptune?": ["Triton is the largest moon of Neptune.", "Triton holds the title for being the largest moon of Neptune."],
    "what's the smallest moon of Uranus?": ["Cupid is the smallest moon of Uranus.", "Cupid holds the title for being the smallest moon of Uranus."],
    "what's the largest moon of Jupiter?": ["Ganymede is the largest moon of Jupiter.", "Ganymede holds the title for being the largest moon of Jupiter."],
    "what's the smallest moon of Saturn?": ["Aegaeon is the smallest moon of Saturn.", "Aegaeon holds the title for being the smallest moon of Saturn."],
    "what's the largest moon of Mars?": ["Phobos is the largest moon of Mars.", "Phobos holds the title for being the largest moon of Mars."],
    "what's the smallest moon of Neptune?": ["Neso is the smallest moon of Neptune.", "Neso holds the title for being the smallest moon of Neptune."],
    "what's the largest moon of Uranus?": ["Titania is the largest moon of Uranus.", "Titania holds the title for being the largest moon of Uranus."],
    "what's the smallest moon of Jupiter?": ["Metis is the smallest moon of Jupiter.", "Metis holds the title for being the smallest moon of Jupiter."],
    "what's the largest moon of Earth?": ["The Moon, also known as Luna, is the largest moon of Earth.", "The Moon holds the title for being the largest moon of Earth."],
    "what's the smallest moon of Earth?": ["There are no natural moons smaller than the Moon orbiting Earth.", "The Moon is the smallest moon of Earth."],
    "what's the largest asteroid?": ["Ceres, also known as a dwarf planet, is the largest asteroid in our solar system.", "Ceres holds the title for being the largest asteroid."],
    "what's the smallest asteroid?": ["There are many small asteroids in our solar system, and it's difficult to determine the absolute smallest.", "Small asteroids come in various sizes, making it challenging to identify the smallest."],
    "what's the largest comet?": ["Comet Hale-Bopp, which made a highly visible appearance in 1997, is one of the largest comets recorded.", "Comet Hale-Bopp holds the title for being one of the largest comets."],
    "what's the smallest comet?": ["Comets vary widely in size, and it's challenging to determine the absolute smallest.", "There are many small comets in our solar system, making it difficult to identify the smallest."],
    "what's the largest dwarf planet?": ["Eris is the largest known dwarf planet in our solar system.", "Eris holds the title for being the largest dwarf planet."],
    "what's the smallest dwarf planet?": ["There are many small dwarf planets in our solar system, and it's challenging to determine the absolute smallest.", "Small dwarf planets come in various sizes, making it difficult to identify the smallest."],
    "what's the largest moon of Pluto?": ["Charon is the largest moon of Pluto.", "Charon holds the title for being the largest moon of Pluto."],
    "what's the smallest moon of Pluto?": ["Styx is one of the smallest moons of Pluto.", "Styx holds the title for being one of the smallest moons of Pluto."],
    "what's the largest moon of Ceres?": ["There are no moons orbiting Ceres.", "Ceres does not have any moons."],
    "what's the smallest moon of Ceres?": ["There are no moons orbiting Ceres.", "Ceres does not have any moons."],
    "what's the largest moon of Eris?": ["There are no moons orbiting Eris.", "Eris does not have any moons."],
    "what's the smallest moon of Eris?": ["There are no moons orbiting Eris.", "Eris does not have any moons."],
    "what's the largest moon of Haumea?": ["There are no moons orbiting Haumea.", "Haumea does not have any moons."],
    "what's the smallest moon of Haumea?": ["There are no moons orbiting Haumea.", "Haumea does not have any moons."],
    "what's the largest moon of Makemake?": ["There are no moons orbiting Makemake.", "Makemake does not have any moons."],
    "what's the smallest moon of Makemake?": ["There are no moons orbiting Makemake.", "Makemake does not have any moons."],
    "what's the largest moon of Eris?": ["There are no moons orbiting Eris.", "Eris does not have any moons."],
    "what's the smallest moon of Eris?": ["There are no moons orbiting Eris.", "Eris does not have any moons."],
    "what's the largest moon of Haumea?": ["There are no moons orbiting Haumea.", "Haumea does not have any moons."],
    "what's the smallest moon of Haumea?": ["There are no moons orbiting Haumea.", "Haumea does not have any moons."],
    "what's the largest moon of Makemake?": ["There are no moons orbiting Makemake.", "Makemake does not have any moons."],
    "what's the smallest moon of Makemake?": ["There are no moons orbiting Makemake.", "Makemake does not have any moons."],
    "what's the largest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "what's the smallest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "what's the largest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the smallest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the largest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the smallest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the largest moon of Salacia?": ["There are no moons orbiting Salacia.", "Salacia does not have any moons."],
    "what's the smallest moon of Salacia?": ["There are no moons orbiting Salacia.", "Salacia does not have any moons."],
    "what's the largest moon of Varuna?": ["There are no moons orbiting Varuna.", "Varuna does not have any moons."],
    "what's the smallest moon of Varuna?": ["There are no moons orbiting Varuna.", "Varuna does not have any moons."],
    "what's the largest moon of Gonggong?": ["There are no moons orbiting Gonggong.", "Gonggong does not have any moons."],
    "what's the smallest moon of Gonggong?": ["There are no moons orbiting Gonggong.", "Gonggong does not have any moons."],
    "what's the largest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the smallest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the largest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the smallest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the largest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "what's the smallest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "what's the largest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the smallest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the largest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the smallest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the largest moon of Salacia?": ["There are no moons orbiting Salacia.", "Salacia does not have any moons."],
    "what's the smallest moon of Salacia?": ["There are no moons orbiting Salacia.", "Salacia does not have any moons."],
    "what's the largest moon of Varuna?": ["There are no moons orbiting Varuna.", "Varuna does not have any moons."],
    "what's the smallest moon of Varuna?": ["There are no moons orbiting Varuna.", "Varuna does not have any moons."],
    "what's the largest moon of Gonggong?": ["There are no moons orbiting Gonggong.", "Gonggong does not have any moons."],
    "what's the smallest moon of Gonggong?": ["There are no moons orbiting Gonggong.", "Gonggong does not have any moons."],
    "what's the largest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the smallest moon of Quaoar?": ["There are no moons orbiting Quaoar.", "Quaoar does not have any moons."],
    "what's the largest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the smallest moon of Orcus?": ["There are no moons orbiting Orcus.", "Orcus does not have any moons."],
    "what's the largest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "what's the smallest moon of Sedna?": ["There are no moons orbiting Sedna.", "Sedna does not have any moons."],
    "Hello!": ["Hey there!", "Greetings, friend!", "Salutations!", "Good day to you!", "Hi, how's your day?", "Greetings and good fortune!", "Hello, may your day be bright!", "Hi, wishing you a splendid day!", "Greetings, may your day be filled with joy!", "Hello, hoping your day is as wonderful as you are!"],
    "Hey there!": ["Hello!", "Greetings!", "Hi!", "How's it going?", "Hey, what's new?", "Hey, good to see you!", "Hello, how have you been?", "Hi, anything exciting happening?", "Hey, long time no see!", "Hello, nice to meet you!"],
    "Hi!": ["Hey!", "Hello!", "Greetings!", "Hi, how are you?", "Hi there, what's on your mind?", "Hello, how can I assist you?", "Hi, nice to see you!", "Hey, what's up?", "Hi, hope you're doing well!", "Hello, how's your day going?"],
    "Howdy!": ["Hello!", "Hey there!", "Hi!", "How are you doing?", "Howdy, partner!", "How's everything?", "How's your day so far?", "Hey, good to see you!", "Howdy, how can I help you?", "Hi, what brings you here today?"],
    "Good to see you!": ["Nice to see you!", "Great to have you here!", "Lovely to see you!", "Hello, how have you been?", "Hey there, how's life treating you?", "Hello, hope you're doing well!", "Hi, how's everything?", "Good to see you again!", "Hi there, missed you!", "Hello, welcome back!"],
    "How are you?": ["I'm doing well, thank you!", "I'm good, thanks!", "All good here, how about you?", "I'm feeling great, thanks for asking!", "Not too bad, thanks for checking in!", "I'm fine, hope you're doing well too!", "I'm doing fine, thanks!", "I'm great, how can I assist you?", "I'm doing well, hope you're having a good day too!", "I'm good, how can I help you?"],
    "Good day!": ["Hello!", "Greetings!", "Hi!", "Good day to you too!", "Good to see you!", "Hello, how's your day?", "Hi there, hope your day is going well!", "Greetings, may your day be filled with joy!", "Hello, wishing you a wonderful day!", "Hi, hope you're having a great day!"],
    "What's up?": ["Hey there!", "How are you?", "Hi!", "Hello!", "What's new with you?", "Hey, anything exciting happening?", "What's happening?", "Hey, what's going on?", "Hey, how's it hanging?", "Hi, what's the news?"],
    "Long time no see!": ["It's been a while!", "Hey there, long time no see!", "Hello, it's been ages!", "Hi, it's been too long!", "Long time indeed!", "Hey, where have you been hiding?", "Hey, missed you!", "Hello, good to see you again!", "Hi there, nice to see you after so long!", "Hey, haven't seen you in forever!"],
    "What's new?": ["Anything exciting happening?", "Tell me the latest!", "What's going on?", "How are things?", "Hey there, what's happening?", "What's up in your world?", "Hi, any news to share?", "Hey, what's the buzz?", "Hey, got any updates for me?", "Hi, what's the word on the street?"],
    "Hi": ["Hey!", "Hello!", "Greetings!", "Hi there!", "How's it going?", "Hey, what's up?", "Hello, how can I assist you?", "Hi, nice to see you!", "Hey, how are you doing?", "Hello, how's your day going?"],
    "Ok": ["Understood!", "Got it!", "Alright!", "Sure thing!", "No problem!", "Okay!", "Sounds good!", "Roger that!", "Gotcha!", "Absolutely!"],
    "Thanks": ["You're welcome!", "No problem!", "My pleasure!", "Happy to help!", "Glad to assist!", "Anytime!", "You got it!", "No worries!", "Don't mention it!", "Of course!"],
    "You can do math": ["Yes, I can help with math. What do you need?", "Sure, math is my forte! What's the problem?", "I'm good with numbers. Shoot your question!", "Mathematics? Count me in!", "I'm ready to crunch some numbers!", "Absolutely, math is my thing.", "No problem, I can handle math questions.", "Of course, I'm here to assist you with math.", "Certainly, fire away with your math query.", "I'm here to help. What do you need?"],
}
